name: module3_task0
run-name: ${{github.actor}} is running workflow
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  run-checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task0/
      - run: make help
