name: module3_task2
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  job1:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20' # replace with your required Go version
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
      - run: sudo ./module3_task1/setup.sh
      - run: make test -C  module3_task2
      - run: make build -C  module3_task2
      - run: make package -C module3_task2
      - run: make run -C  module3_task2
      - run: make stop -C  module3_task2
      - run: make clean -C  module3_task2
