name: module3_task2

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-package:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo ./module3_task1/setup.sh
      - run: make test -C  module3_task2
      - run: make build -C  module3_task2
      - run: make package -C module3_task2
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/main'
        with:
          name: awesome-website
          path: ./module3_task2/awesome-website.zip
      - run: make run -C  module3_task2
      - run: make stop -C  module3_task2
      - run: make clean -C  module3_task2
